//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fest_form.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати номер  .
        /// </summary>
        public static string AddPerformance {
            get {
                return ResourceManager.GetString("AddPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл фонограми обовьязковий .
        /// </summary>
        public static string AddTrack {
            get {
                return ResourceManager.GetString("AddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть вікову групу.
        /// </summary>
        public static string AgeGroup {
            get {
                return ResourceManager.GetString("AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З куліси.
        /// </summary>
        public static string Backstage {
            get {
                return ResourceManager.GetString("Backstage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Керівник групи .
        /// </summary>
        public static string Boosplaceholder {
            get {
                return ResourceManager.GetString("Boosplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хореограф-постановник.
        /// </summary>
        public static string ChoreographerDirector {
            get {
                return ResourceManager.GetString("ChoreographerDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класика.
        /// </summary>
        public static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Концертмейстер.
        /// </summary>
        public static string Concertmaster {
            get {
                return ResourceManager.GetString("Concertmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сучасний / Модерн.
        /// </summary>
        public static string Contemporary_Modern {
            get {
                return ResourceManager.GetString("Contemporary/Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молодша Група ( 9 - 10 років).
        /// </summary>
        public static string DescriptionGroup1 {
            get {
                return ResourceManager.GetString("DescriptionGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середня Група ( 11 - 13 років).
        /// </summary>
        public static string DescriptionGroup2 {
            get {
                return ResourceManager.GetString("DescriptionGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старша Група ( 14 - 16 років).
        /// </summary>
        public static string DescriptionGroup3 {
            get {
                return ResourceManager.GetString("DescriptionGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молодь ( 17 - 20 років).
        /// </summary>
        public static string DescriptionGroup4 {
            get {
                return ResourceManager.GetString("DescriptionGroup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змішані за віком.
        /// </summary>
        public static string DescriptionGroup5 {
            get {
                return ResourceManager.GetString("DescriptionGroup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дует.
        /// </summary>
        public static string Duo {
            get {
                return ResourceManager.GetString("Duo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Введіть правельну пошту.
        /// </summary>
        public static string EmailErrorValidation {
            get {
                return ResourceManager.GetString("EmailErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль (8 - 30 чи більше учасників).
        /// </summary>
        public static string Ensemble_Bigg_ {
            get {
                return ResourceManager.GetString("Ensemble(Bigg)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль (4-7 участників).
        /// </summary>
        public static string Ensemble_Small_ {
            get {
                return ResourceManager.GetString("Ensemble(Small)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Не всі обов&apos;язкові поля заповнені.
        /// </summary>
        public static string ErorrMessage {
            get {
                return ResourceManager.GetString("ErorrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Kількість символів.
        /// </summary>
        public static string ErrorLengthValidation {
            get {
                return ResourceManager.GetString("ErrorLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чорноморськi вiзерунки.
        /// </summary>
        public static string Festname {
            get {
                return ResourceManager.GetString("Festname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фонограма.
        /// </summary>
        public static string FileAdd {
            get {
                return ResourceManager.GetString("FileAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Народний.
        /// </summary>
        public static string Folk {
            get {
                return ResourceManager.GetString("Folk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для участі у фестивалі.
        /// </summary>
        public static string ForeFest {
            get {
                return ResourceManager.GetString("ForeFest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть жанр.
        /// </summary>
        public static string GenreLabel {
            get {
                return ResourceManager.GetString("GenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група 1 .
        /// </summary>
        public static string group1 {
            get {
                return ResourceManager.GetString("group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група 2.
        /// </summary>
        public static string group2 {
            get {
                return ResourceManager.GetString("group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група 3.
        /// </summary>
        public static string group3 {
            get {
                return ResourceManager.GetString("group3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група 4.
        /// </summary>
        public static string group4 {
            get {
                return ResourceManager.GetString("group4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група 5.
        /// </summary>
        public static string group5 {
            get {
                return ResourceManager.GetString("group5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пoшта.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Ім&apos;я та прізвище можуть містити тільки букви, пробіли та дефіси..
        /// </summary>
        public static string NameSymbolValidation {
            get {
                return ResourceManager.GetString("NameSymbolValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аматорський.
        /// </summary>
        public static string OptionsToggleTeamLevelAmateur {
            get {
                return ResourceManager.GetString("OptionsToggleTeamLevelAmateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Професійний.
        /// </summary>
        public static string OptionsToggleTeamLevelProf {
            get {
                return ResourceManager.GetString("OptionsToggleTeamLevelProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Організація.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одеський фаховий коледж мистецтв імені К.Ф. Данькевича.
        /// </summary>
        public static string OrganizationPlaseholder {
            get {
                return ResourceManager.GetString("OrganizationPlaseholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учасник (П.І.Б).
        /// </summary>
        public static string ParticipantNumList {
            get {
                return ResourceManager.GetString("ParticipantNumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість учасників.
        /// </summary>
        public static string ParticipantsNameListLabel {
            get {
                return ResourceManager.GetString("ParticipantsNameListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час виступу.
        /// </summary>
        public static string PerfomanseTime {
            get {
                return ResourceManager.GetString("PerfomanseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва номеру.
        /// </summary>
        public static string PerformanceName {
            get {
                return ResourceManager.GetString("PerformanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про номер.
        /// </summary>
        public static string PerfornamceInfo {
            get {
                return ResourceManager.GetString("PerfornamceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string PersonFirstNameLable {
            get {
                return ResourceManager.GetString("PersonFirstNameLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string PersonLastNameLable {
            get {
                return ResourceManager.GetString("PersonLastNameLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонный номер.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Введіть правильний номер телефону..
        /// </summary>
        public static string PhoneNumberValidation {
            get {
                return ResourceManager.GetString("PhoneNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстраційна форма .
        /// </summary>
        public static string registrationform {
            get {
                return ResourceManager.GetString("registrationform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрацiя.
        /// </summary>
        public static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Поле обов&apos;язкове для заповнення.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соло.
        /// </summary>
        public static string Solo {
            get {
                return ResourceManager.GetString("Solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З точки.
        /// </summary>
        public static string Spot {
            get {
                return ResourceManager.GetString("Spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початкова позиція.
        /// </summary>
        public static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва колективу.
        /// </summary>
        public static string TeameName {
            get {
                return ResourceManager.GetString("TeameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень підготовки колективу.
        /// </summary>
        public static string TeamLevelLabel {
            get {
                return ResourceManager.GetString("TeamLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Керивник колективу (П.І.Б).
        /// </summary>
        public static string TeamLider {
            get {
                return ResourceManager.GetString("TeamLider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тріо.
        /// </summary>
        public static string Trio {
            get {
                return ResourceManager.GetString("Trio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний формат посилання .
        /// </summary>
        public static string ValidationUrlError {
            get {
                return ResourceManager.GetString("ValidationUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання на відеозапис виступу (за наявності).
        /// </summary>
        public static string YouTubeURL {
            get {
                return ResourceManager.GetString("YouTubeURL", resourceCulture);
            }
        }
    }
}
